import { build } from "esbuild";
import { fileURLToPath } from "node:url";
import { assembleHtml } from "../src/document.ts";

const CLIENT_ENTRY = fileURLToPath(new URL("../src/client.ts", import.meta.url));

/** Bundles the browser runtime and returns the complete widget document. Deterministic for a given source tree. */
export async function buildWidgetHtml(): Promise<string> {
  const result = await build({
    entryPoints: [CLIENT_ENTRY],
    bundle: true,
    write: false,
    format: "iife",
    platform: "browser",
    target: "es2020",
    minify: true,
    legalComments: "none",
    logLevel: "silent",
  });
  const output = result.outputFiles[0];
  if (output === undefined) throw new Error("esbuild produced no output");
  return assembleHtml(output.text.trim());
}

/** The TypeScript module that carries the bundle, so the server imports it without a build step at runtime. */
export function generatedModule(html: string): string {
  return (
    "// @generated by `pnpm --filter @evalprop/widget build` (scripts/build.ts). Do not edit; a test fails when it is stale.\n" +
    `export const WIDGET_HTML: string = ${JSON.stringify(html)};\n`
  );
}
