import type { Analysis } from "./analysis.ts";
import type { CardModel } from "./card.ts";
import type { Provenance } from "./common.ts";

/** Minimal valid sample objects for schema tests and for other packages' tests. Not real market data. */
export const sampleProvenance: Provenance = {
  provider: "fixture",
  fetchedAt: "2026-10-01T12:00:00.000Z",
  cached: false,
  confidence: "high",
};

export const sampleAnalysis: Analysis = {
  id: "an_sample",
  ownerUid: "user_sample",
  createdAt: "2026-10-04T12:00:00.000Z",
  engineVersion: "0.0.0",
  pipelineVersion: "0.0.0",
  inputHash: "hash_sample",
  property: {
    formattedAddress: "4417 S Quincy Ave, Tulsa, OK 74105",
    line1: "4417 S Quincy Ave",
    city: "Tulsa",
    state: "OK",
    zip: "74105",
    latitude: 36.1,
    longitude: -95.97,
    propertyType: "single_family",
    beds: 3,
    baths: 2,
    sqft: 1480,
    yearBuilt: 1974,
    listPrice: 239000,
  },
  assumptions: [
    { field: "interestRatePct", value: 7, source: "provided" },
    { field: "vacancyPct", value: 8, source: "assumed" },
    { field: "monthlyRent", value: 2250, source: "lookup", provenance: sampleProvenance },
  ],
  evaluation: {
    verdict: "marginal",
    checks: [{ name: "Cap rate", passed: true, actual: "6.1%", threshold: ">= 6%" }],
    yearOne: {
      grossAnnualRent: 27000,
      vacancyLoss: 2160,
      effectiveRent: 24840,
      operatingExpenses: { propertyTax: 2630, insurance: 2200, hoa: 0, maintenance: 2160, capex: 1350, management: 1987, total: 10327 },
      noi: 14513,
      loanAmount: 179250,
      monthlyPrincipalAndInterest: 1193,
      annualDebtService: 14316,
      annualCashFlow: 197,
      monthlyCashFlow: 17,
      cashInvested: 66920,
      capRatePct: 6.1,
      cashOnCashPct: 0.3,
      dscr: 1.01,
      grossRentMultiplier: 8.85,
      rentToPricePct: 0.94,
      breakEvenOccupancyPct: 91,
      fiftyPercentRuleMonthlyCashFlow: -68,
    },
    hold: {
      years: [
        {
          year: 1,
          grossRent: 27000,
          operatingExpenses: 10327,
          noi: 14513,
          debtService: 14316,
          cashFlow: 197,
          cumulativeCashFlow: 197,
          propertyValue: 246170,
          loanBalance: 176000,
          equity: 70170,
          netSaleProceeds: 55400,
          totalProfit: -11300,
        },
      ],
      cashPaybackMonth: 197,
      breakEvenMonth: 28,
      horizons: [{ years: 10, totalProfit: 104452, equityMultiple: 2.5, irrPct: 10.4 }],
    },
    assumptions: [{ field: "interestRatePct", value: 7, source: "provided" }],
  },
  market: {
    rentComps: {
      estimate: { low: 2100, median: 2250, high: 2400 },
      comps: [
        {
          id: "c1",
          address: "212 Oak St",
          distanceMiles: 0.12,
          beds: 3,
          baths: 2,
          sqft: 1450,
          amount: 2250,
          kind: "asking",
          date: "2026-09-20",
          matchClass: "same-size",
          matchReason: "Same size, 0.1 mi",
        },
      ],
      stepReached: "strict-0.5mi",
      radiusUsedMiles: 0.5,
      confidence: "high",
      notes: [],
    },
    saleComps: null,
    schools: [{ name: "Lincoln Elementary", level: "elementary", rating: 7, distanceMiles: 0.4, assigned: "unknown" }],
    provenance: { rentComps: sampleProvenance },
  },
  advisoryFlags: [{ title: "Tenant-occupied", detail: "Listing says a tenant is in place.", tone: "ok" }],
  dataNotes: [{ section: "schools", severity: "info", message: "Assignment not confirmed by provider." }],
  targetCashOnCashPct: 8,
  maxOfferPrice: 176000,
  breakEvenRent: 2226,
};

export const sampleCard: CardModel = {
  analysisId: "an_sample",
  address: "4417 S Quincy Ave, Tulsa, OK 74105",
  listPrice: 239000,
  analyzedPrice: 239000,
  monthlyRent: 2250,
  rentSource: "lookup",
  verdict: "marginal",
  verdictLabel: "Proceed with caution",
  metrics: { monthlyCashFlow: 17, cashOnCashPct: 0.3, capRatePct: 6.1, dscr: 1.01 },
  maxOffer: { price: 176000, targetCashOnCashPct: 8, vsAnalyzedPricePct: -26 },
  breakEvenMonth: 28,
  irr10Pct: 10.4,
  compsConfidence: "high",
  reportUrl: "https://example.test/r/token",
  dataNotes: [],
};
